### ISSUE TITLE
Fold/Unfold on Custom class not work after IDE restart

### ISSUE THREAD

**Issue by apsueng** [healarconr/logger-folding#13]
Hello, Hope you are fine,

I install and try to use this plugin with a custom logger class : **xx.xx.common.starter.service.LogService**

It would works fine on the first run, but once close and restart of IDE. The folding would not work anymore.

And if I do this two thing which seems to reload the mechanism, it would come back to work again (the arrow/folding start to show).
- Poke change on list of Classes to be fold/unfold in Tools > Logger Folding.   
- Poke some changes on the default folding menu : Editor ? General > Code Folding ,  Uncheck and apply / Recheck and Apply.

:: IDE data below :: 

IntelliJ IDEA 2023.2.5 (Ultimate Edition)
Build #IU-232.10227.8, built on November 9, 2023
Licensed to XXXX
Subscription is active until January 8, 2024.
Runtime version: 17.0.9+7-b1000.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 12
Registry:
    ide.experimental.ui=true

Non-Bundled Plugins:
    google-java-format (1.17.0.0)
    com.intellij.spring.batch (232.8660.142)
    com.intellij.bigdatatools.core (232.10227.8)
    com.intellij.bigdatatools.kafka (232.10227.8)
    com.github.healarconr.loggerfolding (0.5.2)

Kotlin: 232-1.9.0-IJ10227.8

**Comment by healarconr** [comment]
Hi, @apsueng. Thank you for your report. I was able to replicate the problem using the same IntelliJ IDEA version. I have not tested it with the most recent version, but I guess it could also be affected. Unfortunately this plugin project seems to be outdated. Maybe something changed about the way IntelliJ IDEA expects plugins to load persistent state. I will try to find time to take a look at it, but it seems that additional changes should be done to follow the current plugin guidelines.

**Comment by healarconr** [comment]
Hi, @apsueng. Could you please help me to test the [`0.6.0-beta.1`](https://plugins.jetbrains.com/plugin/8242-logger-folding/edit/versions/beta/466067) version of the plugin? I think it solves the problem. The plugin can be downloaded and installed from the disk or the `https://plugins.jetbrains.com/plugins/beta/list` plugin repository can be added. See [Publishing a Plugin](https://plugins.jetbrains.com/docs/intellij/publishing-plugin.html#specifying-a-release-channel):

> When using a non-default release channel, users need to configure a new [custom plugin repository](https://www.jetbrains.com/help/idea/managing-plugins.html?_gl=1*19v2zn9*_ga*ODc0Njk4MDk3LjE2NjkwNDY3ODY.*_ga_9J976DJZ68*MTcwNTA3NDY3MS4xMy4xLjE3MDUwNzU5MzkuMC4wLjA.&_ga=2.222050200.1637190156.1704863936-874698097.1669046786#repos) in their IDE to install your plugin. For example, if you specify `publishPlugin.channels = ['canary']`, then users need to add the `https://plugins.jetbrains.com/plugins/canary/list` repository to install the plugin and receive updates.

**Comment by healarconr** [comment]
This bug was resolved in the release [0.6.0](https://github.com/healarconr/logger-folding/releases/tag/v0.6.0).

**Comment by apsueng** [comment]
Hello @healarconr ,

Sorry I had not been there when you would need me, 

Today I check and see the updates 0.6.0, I tried and confirm it is working like charm!.

Thank you for great updates, 

Best Regards,.
