### ISSUE TITLE
Add support for "Collapse by default"

### ISSUE THREAD

**Issue by Bennett-Lynch** [healarconr/logger-folding#5]
Could you please consider adding support for integrating in with IntelliJ's "Collapse by default" settings? (Editor > General > Code Folding).

Love the plugin. Thanks!

**Comment by healarconr** [comment]
There is a pending release for this issue: #4 and After that I will take a look.

**Comment by Bennett-Lynch** [comment]
Thanks.

Here's another plugin that supports "Collapse by default" (if you find it helpful to have an example):
https://plugins.jetbrains.com/plugin/9320-advanced-java-folding

**Comment by healarconr** [comment]
Thank you, it looks like a good example.

**Comment by healarconr** [comment]
Hi @Bennett-Lynch, I just uploaded the 0.5.0-beta.1 version of the plugin to support collapse by default. The example you mentioned was a really good help. The new version should be available for download in a couple days. It adds a "Logger method calls" checkbox in Settings > Editor > General > Code Folding and the folding should work with Java and Kotlin files. Could you get the new version and help me test it?

**Comment by Bennett-Lynch** [comment]
Would be happy to help test it.  Is there a link for just the plugin jar?  I see the branch created for it, but having some Kotlin dependency issues when I cloned that and trying to build from it.

**Comment by healarconr** [comment]
You can get it from the beta channel in [the plugin page](https://plugins.jetbrains.com/plugin/8242-logger-folding) once it is approved by the JetBrains team.

**Comment by Bennett-Lynch** [comment]
Still hasn't been approved.  Mind building it and uploading it somewhere else?

**Comment by healarconr** [comment]
I just found that you can still download the jar from the JetBrains plugins page even though it is not approved: https://plugins.jetbrains.com/plugin/download?updateId=40425

**Comment by Bennett-Lynch** [comment]
I've only been using it for an hour or so, but it's working great.  Collapsing by default, including my custom logger namespaces.  Exactly what I was looking for, thank you!

**Comment by healarconr** [comment]
Cool! I'm releasing the stable version ([0.5.0](https://plugins.jetbrains.com/plugin/8242-logger-folding/update/40906)) and closing this issue.
